"""Marketing kit: a launch-ready copy bundle for every channel that matters.

Generated by Claude with tool_use to guarantee a typed payload. We give the
model the full blueprint plus (optionally) the live deployment URL so it can
embed it directly into the copy.
"""

from __future__ import annotations

from anthropic import Anthropic
from pydantic import BaseModel, Field

from clonepilot.blueprint.schema import BusinessBlueprint
from clonepilot.config import Config


class TweetThread(BaseModel):
    tweets: list[str] = Field(
        min_length=3,
        max_length=8,
        description=(
            "Sequential tweets in the announcement thread. First tweet is the "
            "hook (<= 240 chars). Last tweet has CTA + URL placeholder."
        ),
    )


class ProductHunt(BaseModel):
    tagline: str = Field(
        description="PH tagline. Aim for <= 60 chars (PH's hard cap)."
    )
    description: str = Field(
        description="PH long description, plain text, 1-2 short sentences."
    )
    first_comment: str = Field(
        description="Maker's first comment on the launch — origin story, 100-180 words."
    )


class HackerNews(BaseModel):
    title: str = Field(
        description="Show HN title. HN convention: 'Show HN: <Product> – <one-line>'. HN's hard cap is 80 chars."
    )
    body: str = Field(
        description="Show HN body, 120-220 words. Honest, no marketing fluff."
    )


class RedditPost(BaseModel):
    subreddit: str = Field(
        description="Best-fit subreddit name, e.g. 'sideproject' or 'indiehackers'."
    )
    title: str = Field(description="Post title. Reddit's hard cap is 300 chars; aim for <= 100.")
    body: str = Field(description="Post body, 150-300 words.")


class LinkedInPost(BaseModel):
    body: str = Field(description="LinkedIn launch post, 80-160 words, professional tone.")


class AdCreative(BaseModel):
    headline: str = Field(description="Ad headline. Aim for <= 40 chars (Google Ads cap).")
    body: str = Field(description="Ad body. Aim for <= 125 chars (Meta primary text cap).")
    image_prompt: str = Field(
        description="Diffusion-model prompt to generate the ad image (no people names)."
    )


class MarketingKit(BaseModel):
    twitter_thread: TweetThread
    product_hunt: ProductHunt
    hacker_news: HackerNews
    reddit: RedditPost
    linkedin: LinkedInPost
    ads: list[AdCreative] = Field(
        min_length=2,
        max_length=4,
        description="Distinct ad angles, not minor variants of each other.",
    )


_SYSTEM_PROMPT = """You are a launch strategist helping an indie hacker announce a new product across X, Product Hunt, Hacker News, Reddit, LinkedIn, and paid ads.

Rules:
- Write like a real founder, not a marketing intern. No "🚀 Excited to announce…". No empty enthusiasm.
- Concrete > abstract. Use the actual numbers, audience, and pain point from the blueprint.
- Each channel has its own voice. HN is engineering-honest. Reddit is conversational. LinkedIn is professional but human. X is punchy.
- If a live URL is provided, embed it naturally in CTAs. If not, leave "{{URL}}" placeholders so the user can fill them.
- ads: think of distinct angles (e.g. before/after, contrarian take, social proof) — not three variants of the same hero shot.

Call submit_kit exactly once."""


def generate_marketing_kit(
    blueprint: BusinessBlueprint,
    cfg: Config,
    live_url: str | None = None,
) -> MarketingKit:
    client = Anthropic(api_key=cfg.require_anthropic())

    tool_schema = MarketingKit.model_json_schema()
    user_prompt = (
        f"Product blueprint (JSON):\n{blueprint.model_dump_json(indent=2)}\n\n"
        f"Live URL: {live_url or '{{URL}} (none yet — use placeholder)'}\n\n"
        "Call submit_kit now."
    )

    response = client.messages.create(
        model=cfg.model_copy,
        max_tokens=4096,
        system=_SYSTEM_PROMPT,
        tools=[
            {
                "name": "submit_kit",
                "description": "Submit the full marketing kit.",
                "input_schema": tool_schema,
            }
        ],
        tool_choice={"type": "tool", "name": "submit_kit"},
        messages=[{"role": "user", "content": user_prompt}],
    )

    for block in response.content:
        if getattr(block, "type", None) == "tool_use":
            return MarketingKit.model_validate(block.input)
    raise RuntimeError(
        f"Claude did not call submit_kit. stop_reason={response.stop_reason}"
    )
