"""SEO starter pack — derived from blueprint + observed keyword volumes.

Pure-ish: no extra API beyond an Anthropic call for title/meta suggestions.
We pass the seed keyword + supporting keywords (from Ahrefs if available,
otherwise generated by Claude from the blueprint).
"""

from __future__ import annotations

from anthropic import Anthropic

from clonepilot.analysis.schema import KeywordVolume, SeoStarterPack
from clonepilot.blueprint.schema import BusinessBlueprint
from clonepilot.config import Config


def generate_seo_pack(
    cfg: Config,
    blueprint: BusinessBlueprint,
    primary_keyword: str,
    supporting: list[KeywordVolume],
) -> SeoStarterPack | None:
    if not cfg.anthropic_api_key:
        return None

    client = Anthropic(api_key=cfg.require_anthropic())

    support_list = [k.keyword for k in supporting[:10]]

    system = (
        "You write SEO meta packs for indie SaaS landing pages. Given a "
        "product brief and a primary keyword, output 5 candidate page titles "
        "(each <= 60 chars, primary keyword present), one meta description "
        "(<= 155 chars, includes CTA verb), and 5 brandable domain suggestions "
        "(prefer .com, .ai, .so). Call submit_seo once."
    )

    bp_brief = (
        f"Product: {blueprint.name} — {blueprint.tagline}\n"
        f"Audience: {blueprint.target_audience}\n"
        f"Differentiation: {blueprint.differentiation}\n"
        f"Primary keyword: {primary_keyword}\n"
        f"Supporting keywords: {', '.join(support_list) if support_list else '(none observed)'}\n"
    )

    tool_schema = {
        "type": "object",
        "properties": {
            "suggested_titles": {
                "type": "array",
                "items": {"type": "string"},
                "minItems": 3,
                "maxItems": 7,
            },
            "suggested_meta_description": {"type": "string"},
            "domain_suggestions": {
                "type": "array",
                "items": {"type": "string"},
                "minItems": 3,
                "maxItems": 8,
            },
        },
        "required": ["suggested_titles", "suggested_meta_description", "domain_suggestions"],
    }

    try:
        response = client.messages.create(
            model=cfg.model_copy,
            max_tokens=1200,
            system=system,
            tools=[
                {
                    "name": "submit_seo",
                    "description": "Submit SEO titles, meta description, and domain ideas.",
                    "input_schema": tool_schema,
                }
            ],
            tool_choice={"type": "tool", "name": "submit_seo"},
            messages=[{"role": "user", "content": bp_brief}],
        )
    except Exception:  # noqa: BLE001
        return None

    payload = _find_tool_use_payload(response)
    if not payload:
        return None

    try:
        return SeoStarterPack(
            primary_keyword=primary_keyword,
            supporting_keywords=support_list,
            suggested_titles=payload.get("suggested_titles", []),
            suggested_meta_description=payload.get("suggested_meta_description", ""),
            domain_suggestions=payload.get("domain_suggestions", []),
        )
    except Exception:  # noqa: BLE001
        return None


def _find_tool_use_payload(response) -> dict:
    for block in response.content:
        if getattr(block, "type", None) == "tool_use":
            return dict(block.input)
    return {}
