"""Static template fragments for the generated Next.js landing page.

Why inline strings: ships cleanly with the Python package (no MANIFEST.in mess),
and a single file is easier to evolve than 12 scattered template files.

Substitution happens in generator.py — placeholders here are deliberately bare
so they survive copy/paste edits.
"""

from __future__ import annotations

PACKAGE_JSON = """{
  "name": "__SLUG__",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "@vercel/analytics": "1.4.1",
    "next": "15.5.18",
    "react": "19.0.0",
    "react-dom": "19.0.0",
    "resend": "4.0.1"
  },
  "devDependencies": {
    "@types/node": "22.10.0",
    "@types/react": "19.0.0",
    "@types/react-dom": "19.0.0",
    "autoprefixer": "10.4.20",
    "postcss": "8.5.1",
    "tailwindcss": "3.4.17",
    "typescript": "5.7.2"
  }
}
"""

NEXT_CONFIG = """/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
};

export default nextConfig;
"""

TSCONFIG = """{
  "compilerOptions": {
    "target": "ES2022",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": { "@/*": ["./*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
"""

TAILWIND_CONFIG = """import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
"""

POSTCSS_CONFIG = """export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
"""

GLOBALS_CSS = """@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  color-scheme: light dark;
}

html {
  scroll-behavior: smooth;
}

body {
  font-feature-settings: "ss01", "cv11";
}
"""

LAYOUT_TSX = """import "./globals.css";
import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/next";

export const metadata: Metadata = {
  title: "__NAME__ — __TAGLINE__",
  description: "__DESCRIPTION__",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-white text-zinc-900 antialiased">
        {children}
        <Analytics />
      </body>
    </html>
  );
}
"""

# page.tsx is rendered via string formatting in generator.py rather than
# placeholder swap, because it needs to inject lists (features, tiers).

GITIGNORE = """node_modules
.next
out
.env*.local
.DS_Store
"""

README_TMPL = """# __NAME__

> __TAGLINE__

Generated by ClonePilot from [__VIDEO_TITLE__](__VIDEO_URL__).

## Run locally

```bash
npm install
npm run dev
```

Open http://localhost:3000.

## Deploy

```bash
npx vercel
```
"""

NEXT_ENV_DTS = """/// <reference types="next" />
/// <reference types="next/image-types/global" />
"""

LEAD_API_ROUTE = """import { NextResponse } from "next/server";
import { Resend } from "resend";

export const runtime = "nodejs";

export async function POST(req: Request) {
  const apiKey = process.env.RESEND_API_KEY;
  const destination = process.env.LEAD_DESTINATION;
  if (!apiKey || !destination) {
    return NextResponse.json(
      { error: "Lead capture is not configured." },
      { status: 503 },
    );
  }

  let payload: { email?: unknown };
  try {
    payload = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON body." }, { status: 400 });
  }

  const email = typeof payload?.email === "string" ? payload.email.trim() : "";
  if (!/^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/.test(email)) {
    return NextResponse.json({ error: "Invalid email." }, { status: 400 });
  }

  const resend = new Resend(apiKey);
  const from = process.env.LEAD_FROM_EMAIL || "onboarding@resend.dev";
  try {
    await resend.emails.send({
      from,
      to: [destination],
      subject: `[__NAME__] new lead: ${email}`,
      text: `New lead from the __NAME__ landing page: ${email}`,
    });
  } catch (err) {
    return NextResponse.json(
      { error: "Could not deliver lead notification." },
      { status: 502 },
    );
  }
  return NextResponse.json({ ok: true });
}
"""

EMAIL_FORM_TSX = """"use client";

import { useState } from "react";

export function EmailCaptureForm({ ctaLabel }: { ctaLabel: string }) {
  const [email, setEmail] = useState("");
  const [status, setStatus] = useState<"idle" | "sending" | "ok" | "error">("idle");
  const [errorMessage, setErrorMessage] = useState("");

  const onSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (status === "sending") return;
    setStatus("sending");
    setErrorMessage("");
    try {
      const res = await fetch("/api/lead", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ email }),
      });
      if (!res.ok) {
        const body = await res.json().catch(() => ({}));
        throw new Error(body.error || `HTTP ${res.status}`);
      }
      setStatus("ok");
      setEmail("");
    } catch (err) {
      setStatus("error");
      setErrorMessage(err instanceof Error ? err.message : "Something went wrong.");
    }
  };

  if (status === "ok") {
    return (
      <p className="mt-6 text-sm text-emerald-700">
        Thanks — we&apos;ll be in touch shortly.
      </p>
    );
  }

  return (
    <form onSubmit={onSubmit} className="mx-auto mt-8 flex max-w-md flex-col gap-2 sm:flex-row">
      <input
        type="email"
        required
        value={email}
        onChange={(e) => setEmail(e.target.value)}
        placeholder="you@company.com"
        className="flex-1 rounded-lg border border-zinc-300 bg-white px-4 py-3 text-sm shadow-sm focus:border-zinc-900 focus:outline-none"
      />
      <button
        type="submit"
        disabled={status === "sending"}
        className="rounded-lg bg-zinc-900 px-5 py-3 text-sm font-semibold text-white hover:bg-zinc-800 disabled:opacity-60"
      >
        {status === "sending" ? "Sending…" : ctaLabel}
      </button>
      {status === "error" ? (
        <span className="block text-sm text-red-600 sm:basis-full">{errorMessage}</span>
      ) : null}
    </form>
  );
}
"""
